# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fb54e4429bd9f099d2bc52842718c870e420caa03c05da06c3021e4623174560b39aeef99ce94c138f2c349241575bfebedf68a0d9dbacf43a742e1264d88cb

test:
  secret_key_base: c7bd137e6fe7109365a3141bee9dba79aae4ffcba6431cef6418c3cdcf54116e9f413648b2069903264ac83220703a6331c613037402308291572c19bc3cc84f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
